# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "54fa24549ec09c7c1bf3f72d21fd4e7a"
name = "learingapp"
handle = "learingapp"
application_url = "https://surveys-solid-spam-advertise.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders"

[auth]
redirect_urls = ["https://surveys-solid-spam-advertise.trycloudflare.com/auth/callback", "https://surveys-solid-spam-advertise.trycloudflare.com/auth/shopify/callback", "https://surveys-solid-spam-advertise.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
